typography_spectrum: 0.4485883079469204
content_rating:
  adult: false
color:
  saturation: 0.903445178642869
  brandStrength: 0.07833858276717365
  rhythmicContrast: 0.1469450043514371
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  lightness: 0.2936827971134335
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7965306928381324
analytics:
  twitter: null
  google: >-
    %3Cscript%3E%20%20%20(function(i%2Cs%2Co%2Cg%2Cr%2Ca%2Cm)%7Bi%5B'GoogleAnalyticsObject'%5D%3Dr%3Bi%5Br%5D%3Di%5Br%5D%7C%7Cfunction()%7B%20%20%20(i%5Br%5D.q%3Di%5Br%5D.q%7C%7C%5B%5D).push(arguments)%7D%2Ci%5Br%5D.l%3D1*new%20Date()%3Ba%3Ds.createElement(o)%2C%20%20%20m%3Ds.getElementsByTagName(o)%5B0%5D%3Ba.async%3D1%3Ba.src%3Dg%3Bm.parentNode.insertBefore(a%2Cm)%20%20%20%7D)(window%2Cdocument%2C'script'%2C'%2F%2Fwww.google-analytics.com%2Fanalytics.js'%2C'ga')%3B%20%20%20%20ga('create'%2C%20'UA-74671536-1'%2C%20'auto')%3B%20%20%20ga('send'%2C%20'pageview')%3B%20%20%3C%2Fscript%3E
  facebook: null
name: SiiiX
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: SiiiX
description: Electric Revolution
purpose: []
